// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH-M1P1NC4v_NiPG7xYf6IG4aFNv_gdAI',
    appId: '1:495587501758:web:2f93c54d412d17e2c060ef',
    messagingSenderId: '495587501758',
    projectId: 'goyo-2f793',
    authDomain: 'goyo-2f793.firebaseapp.com',
    storageBucket: 'goyo-2f793.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCugPZqt5whufFZbZi09Ru2Ugd9042qjL8',
    appId: '1:495587501758:android:cd28775828f7394ec060ef',
    messagingSenderId: '495587501758',
    projectId: 'goyo-2f793',
    storageBucket: 'goyo-2f793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGRS1PxQyOs2HF70iBomMq07_p9lN_4kY',
    appId: '1:495587501758:ios:990801e2b5970adbc060ef',
    messagingSenderId: '495587501758',
    projectId: 'goyo-2f793',
    storageBucket: 'goyo-2f793.appspot.com',
    iosBundleId: 'com.example.firebaseApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGRS1PxQyOs2HF70iBomMq07_p9lN_4kY',
    appId: '1:495587501758:ios:990801e2b5970adbc060ef',
    messagingSenderId: '495587501758',
    projectId: 'goyo-2f793',
    storageBucket: 'goyo-2f793.appspot.com',
    iosBundleId: 'com.example.firebaseApp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH-M1P1NC4v_NiPG7xYf6IG4aFNv_gdAI',
    appId: '1:495587501758:web:1d08d03669c54995c060ef',
    messagingSenderId: '495587501758',
    projectId: 'goyo-2f793',
    authDomain: 'goyo-2f793.firebaseapp.com',
    storageBucket: 'goyo-2f793.appspot.com',
  );
}
